on: pull_request

name: Coverage Reporting

jobs:
  coverage-reporting:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Set up go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Install commands
        run: |
          export GOPATH="$HOME/go"
          PATH="$GOPATH/bin:$PATH"
          go install github.com/jandelgado/gcov2lcov@latest
      - name: Checkout the current branch/ref (${{ github.ref_name }})
        uses: actions/checkout@v3
        with:
          repository: qlikdm/actions-testing
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create coverage report for ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir coverage
          go test ./... -coverpkg=./... -coverprofile=coverage/gcov.info
          gcov2lcov -infile=coverage/gcov.info -outfile=coverage/lcov.info
      - name: Report code coverage
        uses: bartosz347/github-actions-report-lcov@df3091c66dcc578464346310863bb0a3e09d4af4
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 90
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true